create table
  public.count (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    total_collected_num numeric null default '0'::numeric,
    last_collected_num numeric null,
    step numeric null default '15'::numeric,
    name text null,
    "end" numeric null,
    constraint count_pkey primary key (id)
  ) tablespace pg_default;