create table
  public.logs (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    uid uuid not null,
    start numeric not null,
    "end" numeric not null,
    uploaded boolean not null default false,
    "for" bigint null,
    constraint logs_pkey primary key (id),
    constraint logs_for_fkey foreign key ("for") references count(id) on update cascade on delete set null,
    constraint logs_uid_fkey foreign key (uid) references users (uid) on update cascade on delete restrict
  ) tablespace pg_default;
